apiVersion: 1

datasources:
  - name: Jenkins Logs
    type: influxdb
    access: proxy
    user: $INFLUXDB_USER
    url: http://influxdb:8086
    uid: jenkins-logs-datasource # this is for the dashboard definition
    jsonData:
      dbName: jenkins
      httpMode: GET
    secureJsonData:
      password: $INFLUXDB_PASS